Solution for error No route matches [GET]
lsa-mis/mi_classrooms pull request #292
Opened 2023-07-29 15:08 UTC by britaumich

There is a TDX ticker submitted by Moni
[https://teamdynamix.umich.edu/TDNext/Apps/46/Tickets/TicketDet.aspx?TicketID=4775129](https://teamdynamix.umich.edu/TDNext/Apps/46/Tickets/TicketDet.aspx?TicketID=4775129)

She landed somehow on this URL: users/edit.

The pull request has a solution.
1. Removing registerable from the User model will give "No route matches [GET] "/users/edit"
2. To make this error look elegant I added a route and a method "not_found_method"

2023-07-31 15:46 UTC, britaumich commented on app/models/user.rb
> +  devise :database_authenticatable,
I removed recoverable here: [9ad4dc3](https://github.com/lsa-mis/mi_classrooms/pull/292/commits/9ad4dc39d5c9b60cc8a70701c8011a58ad5d68cb)

2023-08-02 18:26 UTC, britaumich commented
@rsmoke I removed the non_found method

2023-08-24 17:59 UTC, rsmoke requested changes
@britaumich, you can also delete the entire app/views/devise folder.

2023-08-24 17:59 UTC, rsmoke commented on app/models/user.rb
please also remove :validatable

2023-08-24 18:40 UTC, britaumich commented on app/models/user.rb
done

2023-08-24 18:41 UTC, britaumich commented
app/views/devise folder is removed

2023-08-24 19:26 UTC, rsmoke approved these changes

2023-08-24 19:27 UTC, merged